django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/v1/', include('movies.urls')),
    path('', include('post.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>', views.post_single, name='post_single'),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):

    class Meta():
        db_table = 'post'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['create']

    title = models.CharField('Заголоваок', max_length=100)
    text = models.TextField('Текст статьи', max_length=1200)
    image = models.ImageField('Изображение', upload_to='post/', blank=True)
    create = models.DateTimeField('Создание', auto_now_add=True)
    update = models.DateTimeField('Обновление', auto_now=True)
    moder = models.BooleanField('Модерация', default=False)

    def __str__(self):
        return self.title


class CommentPost(models.Model):
    class Meta():
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    text = models.TextField('Текст коммента')
    create = models.DateTimeField(auto_now_add=True, verbose_name='Дата коммента')
    moder = models.BooleanField(default=False)

post/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ('text',)

post/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import CommentForm


def post_list(request):
    post = Post.objects.filter(moder=True)
    return render(request, 'post/post_list.html', {'posts': post})


def post_single(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # comment = CommentPost.objects.filter(post=post)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.user = request.user
            comm.post = post
            comm.save()
    else:
        form = CommentForm()
    return render(request, 'post/post_single.html', {'post': post, 'form': form})

templates/post/post_list.html
{% for post in posts %}
    {{ post.create }}<br/>
    <a href="{% url 'post_single' pk=post.id %}">{{ post.title }}</a><br/>
    {% if post.image %}
    <img src="{{ MEDIA_URL }}{{ post.image.url }}" width="300" height="300"> <br/>
    {% endif %}
    {{ post.text }} <hr/>
{% endfor %}

templates/post/post_single.html
{{ post.title }}<br/>
{{ post.create }}<br/>

    {% if post.image %}
    <img src="{{ MEDIA_URL }}{{ post.image.url }}" width="300" height="300"> <br/>
    {% endif %}{{ post.text }}

{{ post.update }} <hr>  <br/>

{% if user.is_active %}
<h4>Комменты</h4>
{% for com in post.commentpost_set.all %}
    {{ com.user }}
    {{ com.text }}<br/>
{% endfor %}

{% endif %}

<p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Отправить">
    </form>
</p>